require('nv-globals')
require('plugins')
require('settings')
require('mappings')

-- PLUGINS
require('nv-autopairs')
require('nv-galaxyline')
-- require('nv-bufferline')
require('nv-barbar')
require('nv-nvimtree')
require('nv-compe')
require('nv-gitsigns')
require('nv-kommentary')
require('nv-treesitter')
require('nv-colorizer')
require('nv-toggleterm')
require('nv-hop')
require('nv-startify')
require('nv-whichkey')
require('nv-telescope')
require('nv-vim-rooter')
require('nv-nrvimr')
require('nv-goyo')
require('nv-vista')
require('nv-vimspector')
require('nv-maximizer')
require('nv-indentguides')
require('nv-scratch')
require('nv-quickscope')
require('nv-suda')
require('nv-emmet')
require('nv-lastplace')
require('nv-vimwiki')

-- LSP
require('lsp')
require('nv-lspinstall')
require('lsp.bash-ls')
require('lsp.css-ls')
require('lsp.docker-ls')
require('lsp.js-ts-ls')
require('lsp.json-ls')
require('lsp.lua-ls')
require('lsp.vim-ls')
require('lsp.yaml-ls')
require('lsp.efm-general-ls')
-- LSP Plugins
require('nv-lspkind')
-- require('nv-lspsaga')
require('nv-lsputil')
-- require('nv-lspsignature')
