require('plugins')
require('settings')
require('mappings')

-- PLUGINS
require('nv-autopairs')
require('nv-galaxyline')
require('nv-bufferline')
require('nv-nvimtree')
require('nv-compe')
require('nv-gitsigns')
require('nv-kommentary')
require('nv-treesitter')
require('nv-colorizer')
require('nv-toggleterm')
require('nv-hop')
-- require('nv-dashboard')
require('nv-startify')
require('nv-whichkey')
require('nv-lspkind')


-- LSP
require('lsp')
require('lsp.bash-ls')
require('lsp.css-ls')
require('lsp.docker-ls')
require('lsp.js-ts-ls')
require('lsp.json-ls')
require('lsp.lua-ls')
require('lsp.vim-ls')
require('lsp.yaml-ls')
